sudo: false
dist: bionic
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- pypy3
matrix:
  fast_finish: true
install:
- travis_retry pip install tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: j0iu6UABKkfcGUjYw1Zj7xv4AwCV6HICPxZ0T/0dg8QtxSJYzAkIpgPw+WUvT+WR5hd5mSea1/6USK9QcNknpHeDCD4ZSCUc2K5UN6Pfh2vjUE0pwZ8L4JK7Z2Tt10pcavR4f1ZjiVs0+MeEWUgm1nXsdWK4oWbpdOkbjYPekSQo+jjTma1m6w7kLhrSweJwitPZ/BQwUUGhcehcOnijYXEsVH0H327YPUhMiNHTFwgiObA7c+mhpu7JtIcAA3W3fMyPKl07bIbXi+XhqlNwxwpWp7a+YlAXsarSERF5oerpfTVVR2kAhtPmhcMiBW7li0Xqd1kuuHwH3mJqGEUHXprLm4t/+IxyKAbdT1nWNuxr4K1X8qBR+eatXU+bxYnXH/fjrkeYp+DdhxbrxYP7FiI5qMNYwZxf9f4ZGYsjFxTZXTZBIbdMpdQdd+BkfR2/aqa3K3N7BKZt+4buvIkmjABUPQ+8pKWvIWVZzAItQCUUb88WTR2xlyi3HX2ZfP6eKDJzks6rEuoY4t/xFndA5fjmQ9zbghnNCF+1vNDHtN1gI8WBOKZZ/ccAO7lY7Oo3wSnsnubLqjc1IUYQazSFQj6mDTayVYFsw0Gyv+X8AC0+BFnl5012wCi4sgGyDLDUt18rI+pTwHd2LGbq2QYt8YHDhX2TD4Qgx4WGtqKsrfc=
  on:
    tags: true
    repo: pmac/urlwait
    python: '3.7'
